e

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -1,10 +1,7 @@
-name: CI
+name: Run tests and deploy
 
 on:
   push:
-    branches:
-      - main
-  pull_request:
     branches:
       - main
 
@@ -18,18 +15,16 @@ jobs:
 
       - name: Set up Node.js
         uses: actions/setup-node@v3
-        with:
-          node-version: '16'
 
       - name: Remove node_modules and package-lock.json
         run: |
           rm -rf node_modules
           rm -f package-lock.json
 
-      - name: Install dependencies
+      - name: Install dependecies
         run: npm install
 
-      - name: Run tests with coverage
+      - name: Run tests
         run: npm test
 
   check-coverage:
@@ -43,11 +38,44 @@ jobs:
       - name: Check test coverage
         run: |
           if [ ! -f ./coverage/coverage-summary.json ]; then
-            echo "Coverage report not found!"
-            exit 1
+          echo "Coverage report not found!"
+          exit 1
           fi
 
           echo "Coverage report found"
 
           COVERAGE=$(cat ./coverage/coverage-summary.json | jq .total.lines.pct)
           echo "Test coverage is ${COVERAGE}%"
+
+          if (( $(echo "$COVERAGE < 90" | bc -l) )); then
+          echo "Test coverage is below 90%, cannot deploy."
+          exit 1
+          fi
+
+  deploy:
+    runs-on: ubuntu-latest
+    needs: check-coverage
+    permissions:
+      contents: read
+      pages: write
+      id-token: write
+
+    steps:
+      - uses: actions/checkout@v4
+      - name: Install modules
+        run: npm install
+
+      - name: Build dist
+        run: npm run build
+
+      - name: Setup pages
+        uses: actions/configure-pages@v3
+
+      - name: Upload dist folder
+        uses: actions/upload-pages-artifact@v1
+        with:
+          path: "./dist"
+
+      - name: Deploy to Github Pages
+        id: deployment
+        uses: actions/deploy-pages@v1
