yml fix

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -1,7 +1,10 @@
-name: Run tests and deploy
+name: CI
 
 on:
   push:
+    branches:
+      - main
+  pull_request:
     branches:
       - main
 
@@ -15,16 +18,18 @@ jobs:
 
       - name: Set up Node.js
         uses: actions/setup-node@v3
+        with:
+          node-version: '16'
 
       - name: Remove node_modules and package-lock.json
         run: |
           rm -rf node_modules
           rm -f package-lock.json
 
-      - name: Install dependecies
+      - name: Install dependencies
         run: npm install
 
-      - name: Run tests
+      - name: Run tests with coverage
         run: npm test
 
   check-coverage:
@@ -38,44 +43,11 @@ jobs:
       - name: Check test coverage
         run: |
           if [ ! -f ./coverage/coverage-summary.json ]; then
-          echo "Coverage report not found!"
-          exit 1
+            echo "Coverage report not found!"
+            exit 1
           fi
 
           echo "Coverage report found"
 
           COVERAGE=$(cat ./coverage/coverage-summary.json | jq .total.lines.pct)
           echo "Test coverage is ${COVERAGE}%"
-
-          if (( $(echo "$COVERAGE < 90" | bc -l) )); then
-          echo "Test coverage is below 90%, cannot deploy."
-          exit 1
-          fi
-
-  deploy:
-    runs-on: ubuntu-latest
-    needs: check-coverage
-    permissions:
-      contents: read
-      pages: write
-      id-token: write
-
-    steps:
-      - uses: actions/checkout@v4
-      - name: Install modules
-        run: npm install
-
-      - name: Build dist
-        run: npm run build
-
-      - name: Setup pages
-        uses: actions/configure-pages@v3
-
-      - name: Upload dist folder
-        uses: actions/upload-pages-artifact@v1
-        with:
-          path: "./dist"
-
-      - name: Deploy to Github Pages
-        id: deployment
-        uses: actions/deploy-pages@v1
